---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-bootstrap
  matrix:
    # Test defaults.
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: fedora29

install:
  # Install test dependencies.
  - pip install molecule==2.19 ansible==2.7.11 docker

before_script: []

script:
  # Run tests.
  - molecule --version
  - ansible --version
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
